# This file has been generated by node2nix 1.11.1. Do not edit!

{ pkgs ? import <nixpkgs> {
    inherit system;
  }
, system ? builtins.currentSystem
, nodejs ? pkgs.nodejs_18
}:
let
  composition = import ./composition.nix { inherit pkgs system nodejs; };
  filterFake = builtins.mapAttrs ( name: drv: drv.override ( old: rec {
    dependencies = builtins.filter ( d: d.version != "fake-version" ) old.dependencies;
    passthru = { inherit dependencies; } // old.passthru or {};
  }));
  update = pkgs.writeShellScript "update-node-packages" ''
    set -e

    cleanup() {
      echo "Killing Caddy..."
      kill "$CADDY_PID"
    }
    trap cleanup EXIT

    echo "Starting caddy in the background as an npmjs mirror with overrides"
    ${pkgs.caddy}/bin/caddy run &
    CADDY_PID=$!
    sleep 2

    ${pkgs.node2nix}/bin/node2nix \
      -i packages.json \
      -c composition.nix \
      --registry http://localhost:3000 \
      --nodejs-18 \
  '';
in
filterFake composition // {
  inherit update;
}

